### ISSUE TITLE
Some problem when executing example.ipynb

### ISSUE THREAD

**Issue by jay1009** [erbloo/dr_cvpr20#2]
Hi, I was trying to execute example.ipynb, but I met some problem like following picture. I found that the X_var.grad gets None in the second step.

![bug](https://user-images.githubusercontent.com/28528806/113566689-c0ff6080-963f-11eb-9b73-954b1b20ac35.jpg)

Can you tell me some information like your pytorch vision or something else?
Thank you.

**Comment by jay1009** [comment]
After I use torch==1.0.0 torchvision==0.2.1, it can run.

**Comment by erbloo** [comment]
> After I use torch==1.0.0 torchvision==0.2.1, it can run.

Sorry for the late reply and glad it worked out.
