### ISSUE TITLE
I'm having the same problem. How can I solve this problem with the latest PyTorch version

### ISSUE THREAD

**Issue by Aristozhang** [erbloo/dr_cvpr20#3]
After I use torch==1.0.0 torchvision==0.2.1, it can run.

_Originally posted by @jay1009 in https://github.com/erbloo/dr_cvpr20/issues/2#issuecomment-813415449_

**Comment by erbloo** [comment]
The bugs that are caused by torch vision change have been fixed. The updated example.ipynb passed the test under torch==1.7.1+cu110 and torchvision==0.8.2+cu110.
