### ISSUE TITLE
inconsistent results

### ISSUE THREAD

**Issue by haolianghan** [erbloo/dr_cvpr20#5]
My experimental results are quite different from those in the paper. The mAP of Faster-RCNN is 7.51%, while that in the paper is 2.5% (COCO dataset). Parameter Settings are the same as those in the paper, step-size = 4, step = 100, epsilon = 16. When step = 2000 (the default value in the code) is adopted, mAP is 2.69%, which is similar to the results in the paper. Is there anything wrong with my experimental setting?

**Comment by erbloo** [comment]
Please provide more details of your code so we can help you. 
Btw, our results can be simply reproduced by "https://github.com/erbloo/bbox_std", which is shown at the bottom of readme.

**Comment by haolianghan** [comment]
Thanks for your reply. My results are produced by "https://github.com/erbloo/bbox_std". Can you tell me more about your environment? I used different environments with different results, but your docker image and all dependencies can not be installed.
![docker_issue](https://user-images.githubusercontent.com/60929185/129545803-ceb18d2f-96c6-45c0-a80e-2e035252fc1c.jpg)

**Comment by wowowoxuan** [comment]
> Thanks for your reply. My results are produced by "https://github.com/erbloo/bbox_std". Can you tell me more about your environment? I used different environments with different results, but your docker image and all dependencies can not be installed.
> ![docker_issue](https://user-images.githubusercontent.com/60929185/129545803-ceb18d2f-96c6-45c0-a80e-2e035252fc1c.jpg)

Hi, Here is our requirements.txt:
[requirements.txt](https://github.com/erbloo/dr_cvpr20/files/7001507/requirements.txt)
Please create a new envoriment and pip install -r requirements.txt

**Comment by haolianghan** [comment]
> 
> 
> > Thanks for your reply. My results are produced by "https://github.com/erbloo/bbox_std". Can you tell me more about your environment? I used different environments with different results, but your docker image and all dependencies can not be installed.
> > ![docker_issue](https://user-images.githubusercontent.com/60929185/129545803-ceb18d2f-96c6-45c0-a80e-2e035252fc1c.jpg)
> 
> Hi, Here is our requirements.txt:
> [requirements.txt](https://github.com/erbloo/dr_cvpr20/files/7001507/requirements.txt)
> Please create a new envoriment and pip install -r requirements.txt

Thanks! My results are consistent with those in the paper.
